### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by CreateSean** [orbital-flight/craft-delete-assets#1]
When I try to install this I get the following error:

```
  Could not find a matching version of package orbital-fli  
  ght/craft-delete-assets. Check the package spelling, you  
  r version constraint and that the package is available i   
  n a stability which matches your minimum-stability (stab   
  le).                                                       
```

Am running craft 4.5.5. and php 8.0.26

please advise

**Comment by mvanbeselaere** [comment]
Hey there, sorry for late reply, 
Did you try to install the plugin manually or from the plugin Store?

You can troubleshoot by updating your composer installation (`composer install`) or updating its cache (`composer clear-cache`).

Let me know if it resolves it or if I can bring further help!

Edit: DUA requirements are currently set as follow:
```
"php": ">=8.0.2",
"craftcms/cms": "^4.3.5"
```

**Comment by CreateSean** [comment]
> Hey there, sorry for late reply, Did you try to install the plugin manually or from the plugin Store?
> 
> You can troubleshoot by updating your composer installation (`composer install`) or updating its cache (`composer clear-cache`).
> 
> Let me know if it resolves it or if I can bring further help!
> 
> Edit: DUA requirements are currently set as follow:
> 
> ```
> "php": ">=8.0.2",
> "craftcms/cms": "^4.3.5"
> ```

I ran composer clear-cache and am running Craft 4.5.5 Still getting the same error when installing via the command line. 

I then attempted to do the install via the plugin store and the page was hanging for 10+ minutes before I cancelled.

**Comment by mvanbeselaere** [comment]
Sounds like something is up with your composer installation, here are a few things you can try:

- Try installing with the **_-w_** flag: `composer require orbital-flight/craft-delete-assets -w && php craft plugin/install delete-assets` 
(This is how the Store installs plugins, ddev command is `ddev composer require orbital-flight/craft-delete-assets -w && ddev craft plugin/install delete-assets`) ;

- Try running `composer update`, which will update all dependencies to compatible versions for every package, then try to install DUA ;

- If that still doesn't work, try to delete your `/vendor` directory and your `composer.lock` file, and then run `composer install` again so it ensures that Composer starts with a clean slate, then try to install DUA ;

- You can then update composer itself with `composer self-update`, then try to install DUA again ;

If none of the above worked, I'd invite you to paste your `composer.json` file content and the details of error messages you encountered below for further investigation!

**Comment by robin-gauthier** [comment]
First time installing this plugin and I've had the same error. 

The error happens on the composer require.

I've managed to workaround by manually adding this to my composer.json, it looks like composer can't find the repo on github

`
"require": {
    "orbital-flight/craft-delete-assets" : "2.0"
  },
`
`"repositories": [
      {
        "type": "vcs",
        "url": "https://github.com/orbital-flight/craft-delete-assets"
      }
  ],
`

**Comment by mvanbeselaere** [comment]
Thanks for letting me know @robin-gauthier, 
It's quite weird as the repo is registered on Craft Console, which to my knowledge should make it available on composer.
I am going to investigate further and keep you updated.

Update: There were discrepancies with my packagist account and its sync with the repo. That is now fixed :)
