### ISSUE TITLE
"Numeric value out of range" error when scanning volumes with many assets

### ISSUE THREAD

**Issue by aelvan** [orbital-flight/craft-delete-assets#2]
![CleanShot 2023-12-13 at 12 26 50](https://github.com/orbital-flight/craft-delete-assets/assets/2675644/efb92276-5996-4cc4-b5e7-d8a6933910d6)

Changing the data type for the columns in question to `bigint`, fixes the issue.

**Comment by mvanbeselaere** [comment]
Thank you @aelvan, gonna deploy a fix asap!

**Comment by mvanbeselaere** [comment]
Fixed in 2.0.1 :)
